function(require_text file_path expected_text)
    file(READ "${file_path}" file_contents)
    string(FIND "${file_contents}" "${expected_text}" match_index)
    if(match_index EQUAL -1)
        message(FATAL_ERROR "${file_path} is missing: ${expected_text}")
    endif()
endfunction()

if(NOT DEFINED NOTEPADNEXT_SOURCE_DIR OR NOT IS_DIRECTORY "${NOTEPADNEXT_SOURCE_DIR}")
    message(FATAL_ERROR "NOTEPADNEXT_SOURCE_DIR must point to the Notepad Next source tree")
endif()

set(linux_desktop "${NOTEPADNEXT_SOURCE_DIR}/deploy/linux/NotepadNext.desktop")
require_text("${linux_desktop}" "Exec=NotepadNext %U")
require_text("${linux_desktop}" "MimeType=text/plain;")

set(flatpak_manifest "${NOTEPADNEXT_SOURCE_DIR}/deploy/flatpak/com.github.dail8859.NotepadNext.yml")
require_text("${flatpak_manifest}" "runtime: org.kde.Platform")
require_text("${flatpak_manifest}" "runtime-version: '6.10'")
require_text("${flatpak_manifest}" "- --persist=.config/NotepadNext")
require_text("${flatpak_manifest}" "- --persist=.local/share/NotepadNext")
require_text("${flatpak_manifest}" "-DAPP_DISTRIBUTION=Flatpak")
require_text("${flatpak_manifest}" "^Exec=NotepadNext %f$|Exec=NotepadNext @@u %U @@")
require_text("${flatpak_manifest}" "^Exec=NotepadNext %U$|Exec=NotepadNext @@u %U @@")

set(macos_plist "${NOTEPADNEXT_SOURCE_DIR}/deploy/macos/info.plist")
require_text("${macos_plist}" "CFBundleDocumentTypes")
require_text("${macos_plist}" "CFBundleTypeRole")
require_text("${macos_plist}" "<string>Editor</string>")
require_text("${macos_plist}" "LSHandlerRank")
require_text("${macos_plist}" "<string>public.text</string>")

set(windows_installer "${NOTEPADNEXT_SOURCE_DIR}/installer/installer.nsi")
require_text("${windows_installer}" [=[Software\Classes\Applications\NotepadNext.exe\shell\open\command]=])
require_text("${windows_installer}" [=[Software\Classes\SystemFileAssociations\text\OpenWithList\NotepadNext.exe]=])
require_text("${windows_installer}" [=[Software\Classes\*\shell\NotepadNext\command]=])
require_text("${windows_installer}" [=[DeleteRegKey SHCTX "Software\Classes\Applications\NotepadNext.exe"]=])
require_text("${windows_installer}" [=[DeleteRegKey SHCTX "Software\Classes\SystemFileAssociations\text\OpenWithList\NotepadNext.exe"]=])
require_text("${windows_installer}" [=[DeleteRegKey SHCTX "Software\Classes\*\shell\NotepadNext"]=])
